=== MiguelBM1980/XML_Ej2/Biblioteca_carlos.dtd
<!ELEMENT biblioteca (libros|revistas|periodicos)*>

        <!-- Estructura de los libros-->

        <!ELEMENT libros (libro)*>
        <!ELEMENT libro (titulo|capitulos|indice|sinopsis)*>
        <!ATTLIST libro
                id CDATA #REQUIRED
                no_paginas CDATA #REQUIRED
                tipo_clase CDATA #REQUIRED>
        <!ELEMENT titulo (#PCDATA)>
        <!ELEMENT capitulos (capitulo)*>
        <!ELEMENT capitulo (contenido)*>
        <!ATTLIST capitulo
                no_paginas CDATA #REQUIRED>
        <!ATTLIST contenido
                enlace CDATA #REQUIRED>
        <!ELEMENT sinopsis (#PCDATA)>

        <!-- Estructura de las revistas-->

        <!ELEMENT revistas (revista)*>
        <!ELEMENT revista (titulo|indice|numero|secciones)*>
        <!ATTLIST revista
                id CDATA #REQUIRED
                no_paginas CDATA #REQUIRED
                tipo_clase CDATA #REQUIRED>
        <!ELEMENT numero (#PCDATA)>
        <!ATTLIST seccion
                no_paginas CDATA #IMPLIED>

        <!-- Estructura de los periÃ³dicos-->
        <!ELEMENT periodicos (periodico)*>
        <!ELEMENT periodico (indice|secciones)*>
        <!ATTLIST periodico
                fecha_publicacion CDATA #REQUIRED
                id CDATA #REQUIRED
                tipo_clase CDATA #REQUIRED>
        <!ATTLIST seccion
                tipo_clase CDATA #IMPLIED>
        <!ELEMENT articulo (contenido)*>
        <!ATTLIST articulo
                autor CDATA #REQUIRED>
        <!ATTLIST contenido
                enlace CDATA #REQUIRED>

                <!-- Elementos comunes-->

                <!ELEMENT indice (#PCDATA)>
                <!ELEMENT seccion (contenido|articulo)*>
                <!ELEMENT secciones (seccion|articulo)*>
                <!ELEMENT contenido (#PCDATA)>

=== MiguelBM1980/XML_Ej2/Biblioteca_completa_carlos.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE biblioteca SYSTEM "Biblioteca_carlos.dtd">
<biblioteca>
(articulos | contenido_Seccion)
    <!--LIBROS-->
<libros>
    <libro id="L0001" tipo_clase="didactico" no_paginas = "180">
        <titulo>Matemáticas aplicadas a las ciencias sociales</titulo>
        <capitulos>
          <capitulo no_paginas="60">
            <contenido enlace="http://www.numbers.com"></contenido>
          </capitulo>
          <capitulo no_paginas="80">
            <contenido enlace="http://www.matematicas.es"></contenido>
          </capitulo>
          <capitulo no_paginas="40">
            <contenido enlace="http://matesbachillerato.es"></contenido>
          </capitulo>
        </capitulos>
        <indice>Unidades didácticas</indice>
        <sinopsis>Resumen</sinopsis>
    </libro>

    <libro id="L0002" tipo_clase="novela" no_paginas="2000">
        <titulo>Los pilares de la tierra</titulo>
        <capitulos>
          <capitulo no_paginas="600">
            <contenido enlace="http://www.google.com"></contenido>
          </capitulo>
          <capitulo no_paginas="700">
            <contenido enlace="http://www.google.es"></contenido>
          </capitulo>
          <capitulo no_paginas="700">
            <contenido enlace="http://www.google.uk"></contenido>
          </capitulo>
        </capitulos>
        <indice>Índice</indice>
        <sinopsis>>Resumen</sinopsis>
    </libro>

    <libro id="L0003" tipo_clase="infantil" no_paginas="20">
        <titulo>La amiga más amiga de la hormiga Miga</titulo>
        <capitulos>
          <capitulo no_paginas="7">
              <contenido enlace="http://www.librosinantiles.com"></contenido>
          </capitulo>
          <capitulo no_paginas="6">
            <contenido enlace="http://www.cuentosparaniños.es"></contenido>
          </capitulo>
          <capitulo no_paginas="7">
            <contenido enlace="http://www.elbarcodevapor.es"></contenido>
          </capitulo>
        </capitulos>
        <indice>Índice</indice>
        <sinopsis>Resumen</sinopsis>
    </libro>
</libros>

    <!--REVISTAS-->

<revistas>
    <revista id="R0001" tipo_clase="informatica" no_paginas="20">
        <titulo>Computer hoy</titulo>
        <indice>Índice de contenido</indice>
        <numero>202</numero>
        <secciones>
            <seccion no_paginas="10">
                <contenido enlace="http://https://computerhoy.com/tecnologia"></contenido>
            </seccion>
            <seccion no_paginas="10">
                <contenido enlace="http://https://computerhoy.com/gaming"></contenido>
             </seccion>
        </secciones>
    </revista>

    <revista id="R0002" tipo_clase="coches" no_paginas="40">
        <titulo>Motor 16</titulo>
        <indice>Índice de contenido</indice>
        <numero>333</numero>
        <secciones>
            <seccion no_paginas="20">
                <contenido enlace="http://https://motor16.es/novedades"></contenido>
            </seccion>
            <seccion no_paginas="20">
                <contenido enlace="http://https://motor16.es/vintage"></contenido>
             </seccion>
        </secciones>
    </revista>

    <revista id="R0003" tipo_clase="corazon" no_paginas="27">
        <titulo>Hola</titulo>
        <indice>Índice de contenido</indice>
        <numero>103</numero>
        <secciones>
            <seccion no_paginas="17">
                <contenido enlace="http://https://www.hola.es/familiareal"></contenido>
            </seccion>
            <seccion no_paginas="10">
                <contenido enlace="http://https://www.hola.es/nutricion"></contenido>
             </seccion>
        </secciones>
    </revista>

    <revista id="R0004" tipo_clase="investigacion" no_paginas="60">
        <titulo>Springer</titulo>
        <indice>Índice de contenido</indice>
        <secciones>
            <seccion no_paginas="30">
                <contenido enlace="https://www.springer.com/journal/426"></contenido>
            </seccion>
            <seccion no_paginas="30">
                <contenido enlace="https://www.springer.com/journal/426/updates/17818222"></contenido>
             </seccion>
        </secciones>
    </revista>

    
</revistas>

    <!--PERIÓDICOS-->

<periodicos>
    <periodico id="P0001" tipo_clase="nacionales" fecha_publicacion="01/07/2013">
        <indice>Índice</indice>
        <secciones>
            <seccion tipo_clase="deportes">                
                <articulo autor="Macarena Vidal">
                    <contenido enlace="https://elpais.com/deportes/2021-05-18/japon-contra-tokio.html"></contenido>
                </articulo> 
            </seccion>
            <seccion tipo_clase="nacional">
                <articulo autor="María García">
                    <contenido enlace="https://elpais.com/espana/2021-05-18/el-ejercito-se-despliega-para-controlar-las-calles-de-ceuta-tras-la-entrada-de-5000-inmigrantes.html"></contenido>
                </articulo> 
            </seccion>
            <articulo autor="Ainhoa Campos"> 
                <contenido enlace= "https://elpais.com/espana/2021-05-17/un-millar-de-personas-llegan-a-nado-a-ceuta-en-plena-escalada-de-tension-diplomatica-con-marruecos.html"></contenido>
            </articulo>
            
            <seccion tipo_clase="internacional">
                <articulo autor="Juan López">
                    <contenido enlace="https://elpais.com/internacional/2021-05-18/un-triple-golpe-a-las-fabricas-las-escuelas-y-los-hospitales.html"></contenido>
                </articulo> 
                <articulo autor="Amanda Mars">
                    <contenido enlace="https://elpais.com/internacional/2021-05-17/biden-defiende-el-alto-el-fuego-en-gaza-en-una-conversacion-con-netanyahu.html"></contenido>
                </articulo> 
            </seccion>
        </secciones>
    </periodico>

    <periodico id="P0002" tipo_clase="internacionales" fecha_publicacion="18/05/2021">

        <indice>Índice</indice>
        <secciones>
            <seccion tipo_clase="economia">
                <articulo autor="Jan Adams">
                    <contenido enlace="https://www.nytimes.com/2021/05/18/business/economy/china-bank-debt-huarong.html"></contenido>
                </articulo>
            </seccion>
            <seccion tipo_clase="opnion">
                <articulo autor="Christopher Futterman">
                    <contenido enlace="https://www.nytimes.com/2021/05/18/opinion/israel-palestinians-conflict-injuries-hospital.html"></contenido>
                </articulo>
            </seccion>

            <seccion tipo_clase="deportes">
                <articulo autor="Talya Minsberg">
                    <contenido enlace="https://www.nytimes.com/2021/05/18/business/economy/china-bank-debt-huarong.html"></contenido>
                </articulo>
            </seccion>

            <seccion tipo_clase="nacional">
                <articulo autor="Hannah Smith">
                    <contenido enlace="https://www.nytimes.com/video/us/politics/100000007769035/biden-ford-electric-vehicles-infrastructure.html"></contenido>
                </articulo>
            </seccion>

            <seccion tipo_clase="internacional">
                <articulo autor="Steven Erlanger">
                    <contenido enlace="https://www.nytimes.com/2021/05/18/world/europe/europe-israel-palestinians-gaza-ceasefire.html"></contenido>
                </articulo>
            </seccion>
        </secciones>
    </periodico>
</periodicos>

</biblioteca>
